fragment project on Project {
	title
	description
	content
	slug
	media {
		data {
			id
			attributes {
				...media
			}
		}
	}
	date
	tags {
		data {
			id
			attributes {
				...tag
			}
		}
	}
	links {
		title
		url
		type
	}
	banner {
		data {
			attributes {
				...media
			}
		}
	}
}
