services:
  api:
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    image: registry.ham-san.net/ham-san-net-api:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./.env:/usr/src/app/dist/apps/api/.env
      - ./public/uploads:/usr/src/app/dist/apps/api/public/uploads
      - ./data:/usr/src/app/dist/apps/api/data
      # - ./api/config:/usr/src/app/dist/apps/api/config
      # - ./api/src:/usr/src/app/dist/apps/api/src
    ports:
      - 1337:1337
    command: ['bun', 'run', 'start']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - internal-services
  client:
    container_name: astro
    env_file: .env
    restart: unless-stopped
    image: registry.ham-san.net/ham-san-net-astro:latest
    environment:
      PRIVATE_BACKEND_API_URL: http://api:1337
      PORT: 4125
    ports:
      - 4125:4125
    networks:
      - internal-services

networks:
  internal-services:
    external: true
