query fetchProjects($limit: Int = 100, $locale: I18NLocaleCode) {
  projects(
    pagination: { pageSize: $limit }
    sort: ["isFeatured:desc", "date:desc"]
    locale: $locale
  ) {
    id: documentId
    ...projectPreview
    localizations {
      ...projectPreview
    }
  }
}
