query fetchProjects($limit: Int = 100, $locale: I18NLocaleCode) {
  projects(
    pagination: { pageSize: $limit }
    sort: ["isFeatured:desc", "date:desc"]
    locale: $locale
  ) {
    data {
      id
      attributes {
        ...projectPreview
        localizations {
          data {
            attributes {
              ...projectPreview
            }
          }
        }
      }
    }
  }
}
