query fetchBlogPosts(
  $limit: Int = 100
  $locale: I18NLocaleCode
) {
  blogs(
    pagination: { pageSize: $limit }
    sort: ["isFeatured:desc", "date:desc"]
    locale: $locale
  ) {
    id: documentId
    ...blog
  }
}
