query fetchHomePage($locale: I18NLocaleCode) {
  projects(
    pagination: { pageSize: 3 }
    filters: { isFeatured: { eq: true } }
    sort: ["isFeatured:desc", "date:desc"]
    locale: $locale
  ) {
    id: documentId
    ...projectPreview
    localizations {
      ...projectPreview
    }
  }
  homepage(locale: $locale) {
    introduction
    introductionImage {
      ...media
    }
    hero
    heroSubtitle
    heroImage {
      ...media
    }
  }
}
