query getTagBySlug($slug: String, $locale: I18NLocaleCode) {
  tags(filters: { slug: { eq: $slug } }, locale: $locale) {
    id: documentId
    ...tag
    projects(sort: ["isFeatured:desc", "date:desc"]) {
      id: documentId
      ...projectPreview
    }
    experiences(sort: ["start:desc"]) {
      id: documentId
      ...experience
    }
  }
}
