fragment blog on Blog {
  title
  description
  content
  slug
  category {
    name
  }
  thumbnail {
    ...media
  }
  tags {
    ...tag
  }
  banner {
    ...media
  }
  localizations {
    locale
    slug
  }
  createdAt
}
