fragment project on Project {
  title
  description
  content
  slug
  isActive
  locale
  category {
    name
  }
  media {
    ...media
  }
  date
  finishedDate
  tags {
    ...tag
  }
  links {
    title
    url
    type
  }
  banner {
    ...media
  }
  localizations {
    locale
    slug
  }
}
