fragment projectPreview on Project {
  title
  description
  slug
  isActive
  locale
  category {
    name
  }
  media {
    ...media
  }
  banner {
    ...media
  }
  date
  finishedDate
  links {
    title
    url
    type
  }
  tags {
    ...tag
  }
}
