query fetchAboutMe($locale: I18NLocaleCode) {
	aboutMe(locale: $locale) {
		data {
			attributes {
				introduction
			}
		}
	}
	experiences(locale: $locale, sort: ["start:desc"]) {
		data {
			attributes {
				...experience
			}
		}
	}
	educations(locale: $locale, sort: ["start:desc"]) {
		data {
			attributes {
				...education
			}
		}
	}
	tags(locale: $locale, sort: ["order:asc"], pagination: { limit: 100 }) {
		data {
			attributes {
				...tag
			}
		}
	}
}
