query fetchProjects($limit: Int, $isFeatured: Boolean, $locale: I18NLocaleCode) {
	projects(
		pagination: { pageSize: $limit }
		filters: { isFeatured: { eq: $isFeatured } }
		locale: $locale
	) {
		data {
			id
			attributes {
				...project
			}
		}
	}
}
