query fetchProjects($limit: Int, $isFeatured: Boolean) {
	projects(pagination: { pageSize: $limit }, filters: { isFeatured: { eq: $isFeatured } }) {
		data {
			id
			attributes {
				...project
			}
		}
	}
}
