query fetchProjects($limit: Int = 100, $isFeatured: Boolean, $locale: I18NLocaleCode) {
	projects(
		pagination: { pageSize: $limit }
		filters: { isFeatured: { eq: $isFeatured } }
		sort: ["isFeatured:desc", "date:desc"]
		locale: $locale
	) {
		data {
			id
			attributes {
				title
				description
				slug
				isActive
				category {
					data {
						id
						attributes {
							name
						}
					}
				}
				media(pagination: { pageSize: 1 }) {
					data {
						id
						attributes {
							...media
						}
					}
				}
				date
				tags {
					data {
						id
						attributes {
							...tag
						}
					}
				}
				links {
					title
					url
					type
				}
			}
		}
	}
}
