import type { HobbyLink } from '~/utils/hobby-content';

export type HobbyEmbedProps = {
  title?: string | null;
  description?: string;
  body?: string;
  images?: string[];
  links?: HobbyLink[];
  nestedPages?: Array<{ title: string; href: string }>;
  statusLabel?: string;
  moduleLabel?: string;
  moduleTitle?: string;
  moduleDescription?: string;
  updatedPrefix?: string;
  liveContentLabel?: string;
  emptySourceLabel?: string;
  emptySourceStateLabel?: string;
  nestedSourcePagesLabel?: string;
  sourceNoteAttachedLabel?: string;
  statusMetricLabel?: string;
  linksMetricLabel?: string;
  updatedMetricLabel?: string;
  pagesMetricLabel?: string;
  profilesMetricLabel?: string;
  sourceMetricLabel?: string;
  linkedPhotoSourcesLabel?: string;
  noImagesLabel?: string;
  noLinksLabel?: string;
  sourceNoteLabel?: string;
  noFeedLabel?: string;
  noTypingProfilesLabel?: string;
  sourceNoteUseLabel?: string;
  nestedSourcePageUseLabel?: string;
  openSourcePageLabel?: string;
  noAlgorithmSetsLabel?: string;
  audioUnavailableLabel?: string;
  playedLabel?: string;
  audioStartsAfterTapLabel?: string;
  sourcePagesAttachedLabel?: string;
  updatedAt?: string;
  status?: 'active' | 'inactive';
};
