export const roomCopy = {
  en: {
    room: 'My room',
    scene: 'An interactive 3D room',
    welcome: 'Come on in',
    title: 'A room of my own.',
    intro: 'Work on the monitor. Notes on the desk. Hobbies on the shelf. Take a look around.',
    enter: 'Enter room',
    loading: 'Preparing the room…',
    loadingDescription: 'Loading…',
    conventional: 'Browse the website',
    controls:
      'Click the canvas to lock cursor · WASD to move · Mouse or arrows to look · Click an object to explore',
    mobileControls: 'Drag to look · Tap the floor to move · Tap an object to explore',
    destinations: 'Explore',
    namecard: 'Namecard',
    events: 'Events',
    exit: 'Leave room',
    lieDown: 'Lie down',
    standUp: 'Stand up',
    resting: 'Resting · movement locked · Esc to stand up',
    closet: 'Closet',
    closetOpen: 'Open closet',
    closetClose: 'Close closet',
    fullPage: 'Open page',
    close: 'Return to room',
    examine: 'Examine',
    light: 'Light',
    lightOn: 'Turn lights on',
    lightOff: 'Turn lights off',
    lightLeft: 'Left light',
    lightRight: 'Right light',
    lightStateOn: 'On',
    lightStateOff: 'Off',
    lightAuto: 'Tokyo automatic',
    curtains: 'Curtains',
    curtainsOpen: 'Open curtains',
    curtainsClose: 'Close curtains',
    curtainsAuto: 'Tokyo automatic',
    related: 'Related pages',
    content: 'Page content',
    failed: 'The room could not load. You can still explore every page below.',
    look: 'Click to explore',
    about: 'About',
    contact: 'Contact',
    tags: 'Tags',
    piano: 'Piano',
    typing: 'Typing / Steno',
    darts: 'Darts',
    rubik: 'Rubik',
    yoyo: 'Yoyo',
    penspinning: 'Pen Spinning',
    kendama: 'Kendama',
    cardistry: 'Cardistry / Magic',
    dartsIntro: 'Aim on the board, then throw',
    dartsScore: 'Score',
    dartsThrows: 'Throws',
    dartsReset: 'Reset game',
    dartsBoard: 'Dartboard aiming surface',
    dartsAim: 'Aim set',
    dartsReady: 'Choose a spot on the board.',
    dartsThrow: 'Throw dart',
    dartsResult: 'Result',
    dartsBullseye: 'Bullseye · 50',
    dartsOuter: 'Outer bull · 25',
    dartsSingle: 'Single · 10',
    dartsMiss: 'Miss · 0',
    penlight: 'Penlights',
    games: {
      score: 'Score',
      best: 'Best',
      combo: 'Combo',
      start: 'Start',
      reset: 'Reset',
      piano: {
        intro: 'Play with the mouse or keys A W S E D F T G Y H U J K O L P ;',
        playAlong: 'Play along',
        progress: 'Notes',
        done: 'Song cleared'
      },
      typing: {
        intro: 'Type the line as fast and cleanly as you can',
        next: 'Next line',
        wpm: 'WPM',
        accuracy: 'Accuracy',
        done: 'Line done'
      },
      rubik: {
        intro: 'Scramble, then solve. Buttons or keys U D L R F B, Shift for reverse',
        scramble: 'Scramble',
        moves: 'Moves',
        time: 'Time',
        solved: 'Solved'
      },
      yoyo: {
        intro: 'Throw, let it sleep, then bind it back before the spin dies. Space throws and binds, T does a trick',
        throw: 'Throw',
        bind: 'Bind',
        trick: 'Around the world',
        dead: 'The yoyo stopped spinning',
        spin: 'Spin'
      },
      penspinning: {
        intro: 'Pass the pen when it crosses the glowing arc. Space or click',
        pass: 'Pass',
        drop: 'Dropped it',
        speed: 'Speed'
      },
      kendama: {
        intro: 'Pull the tama up while it swings through the glowing zone. Space or click',
        pull: 'Pull up',
        big: 'Big cup',
        small: 'Small cup',
        spike: 'Spike',
        miss: 'Missed'
      },
      cardistry: {
        intro: 'Watch the ace, follow the shuffle, then pick it',
        deal: 'Deal',
        pick: 'Pick a card',
        right: 'Found the ace',
        wrong: 'Not this one',
        level: 'Level'
      },
      penlight: {
        intro: 'Wave the matching colour when the light hits the ring. Pads or keys 1 to 5',
        perfect: 'Perfect',
        great: 'Great',
        miss: 'Miss'
      }
    },
    blocked: 'Arrow keys look around. WASD moves through the room.'
  },
  ja: {
    room: '私の部屋',
    scene: '操作できる3Dの部屋',
    welcome: 'ようこそ',
    title: '私の部屋へ。',
    intro: 'モニターには制作物。机にはノート。棚には趣味。自由に見て回ってください。',
    enter: '部屋に入る',
    loading: '部屋を準備しています…',
    loadingDescription: '読み込み中…',
    conventional: '通常のサイトを見る',
    controls:
      'キャンバスをクリックしてカーソルを固定 · WASDで移動 · マウス/矢印で見回す · 物をクリックして読む',
    mobileControls: 'ドラッグで見回す · 床をタップして移動 · 物をタップして読む',
    destinations: 'コンテンツ',
    namecard: '名刺',
    events: 'イベント',
    exit: '部屋を出る',
    lieDown: '横になる',
    standUp: '起き上がる',
    resting: '休憩中 · 移動固定 · Escで起き上がる',
    closet: 'クローゼット',
    closetOpen: 'クローゼットを開く',
    closetClose: 'クローゼットを閉じる',
    fullPage: 'ページを開く',
    close: '部屋に戻る',
    examine: '調べる',
    light: '照明',
    lightOn: '照明を点ける',
    lightOff: '照明を消す',
    lightLeft: '左の照明',
    lightRight: '右の照明',
    lightStateOn: '点灯',
    lightStateOff: '消灯',
    lightAuto: '東京時刻に戻す',
    curtains: 'カーテン',
    curtainsOpen: 'カーテンを開く',
    curtainsClose: 'カーテンを閉じる',
    curtainsAuto: '東京時刻に戻す',
    related: '関連ページ',
    content: 'ページの内容',
    failed: '部屋を読み込めませんでした。下のリンクから各ページをご覧いただけます。',
    look: 'クリックして読む',
    about: '自己紹介',
    contact: 'お問い合わせ',
    tags: 'タグ',
    piano: 'ピアノ',
    typing: 'タイピング / ステノ',
    darts: 'ダーツ',
    rubik: 'ルービックキューブ',
    yoyo: 'ヨーヨー',
    penspinning: 'ペンスピニング',
    kendama: 'けん玉',
    cardistry: 'カーディストリー / マジック',
    dartsIntro: 'ボードを狙ってから投げてください',
    dartsScore: 'スコア',
    dartsThrows: '投数',
    dartsReset: 'ゲームをリセット',
    dartsBoard: '狙うダーツボード',
    dartsAim: '狙いを設定',
    dartsReady: 'ボード上の場所を選んでください。',
    dartsThrow: 'ダーツを投げる',
    dartsResult: '結果',
    dartsBullseye: 'ブルズアイ · 50',
    dartsOuter: 'アウターブル · 25',
    dartsSingle: 'シングル · 10',
    dartsMiss: 'ミス · 0',
    penlight: 'ペンライト',
    games: {
      score: 'スコア',
      best: 'ベスト',
      combo: 'コンボ',
      start: 'スタート',
      reset: 'リセット',
      piano: {
        intro: 'マウスかキー A W S E D F T G Y H U J K O L P ; で演奏',
        playAlong: 'いっしょに弾く',
        progress: '音',
        done: 'クリア'
      },
      typing: {
        intro: '表示された文をできるだけ速く正確に入力',
        next: '次の文',
        wpm: 'WPM',
        accuracy: '正確さ',
        done: '完了'
      },
      rubik: {
        intro: 'スクランブルして揃えよう。ボタンかキー U D L R F B、Shiftで逆回転',
        scramble: 'スクランブル',
        moves: '手数',
        time: 'タイム',
        solved: '完成'
      },
      yoyo: {
        intro: '投げて回転させ、止まる前に戻そう。スペースで投げる・戻す、Tでトリック',
        throw: '投げる',
        bind: '戻す',
        trick: 'アラウンド・ザ・ワールド',
        dead: '回転が止まった',
        spin: '回転'
      },
      penspinning: {
        intro: 'ペンが光る弧を通る瞬間にパス。スペースかクリック',
        pass: 'パス',
        drop: '落とした',
        speed: 'スピード'
      },
      kendama: {
        intro: '玉が光るゾーンを通る瞬間に引き上げよう。スペースかクリック',
        pull: '引き上げる',
        big: '大皿',
        small: '小皿',
        spike: 'とめけん',
        miss: '失敗'
      },
      cardistry: {
        intro: 'エースを覚えて、シャッフルを目で追い、当てよう',
        deal: '配る',
        pick: 'カードを選んで',
        right: '正解',
        wrong: 'はずれ',
        level: 'レベル'
      },
      penlight: {
        intro: '光がリングに重なった瞬間に同じ色を振ろう。パッドかキー 1〜5',
        perfect: 'パーフェクト',
        great: 'グレート',
        miss: 'ミス'
      }
    },
    blocked: '矢印キーで見回せます。WASDで部屋を移動できます。'
  },
  th: {
    room: 'ห้องของผม',
    scene: 'ห้องสามมิติที่สำรวจได้',
    welcome: 'เชิญเข้ามาเลย',
    title: 'ห้องของผมเอง',
    intro: 'ผลงานอยู่ที่จอ บันทึกอยู่บนโต๊ะ งานอดิเรกอยู่บนชั้น ลองเดินดูได้เลย',
    enter: 'เข้าห้อง',
    loading: 'กำลังเตรียมห้อง…',
    loadingDescription: 'กำลังโหลด…',
    conventional: 'ดูเว็บไซต์แบบปกติ',
    controls:
      'คลิกแคนวาสเพื่อล็อกเคอร์เซอร์ · WASD เพื่อเดิน · เมาส์หรือปุ่มลูกศรเพื่อมอง · คลิกสิ่งของเพื่อดูเนื้อหา',
    mobileControls: 'ลากเพื่อมองรอบห้อง · แตะพื้นเพื่อเดิน · แตะสิ่งของเพื่อดูเนื้อหา',
    destinations: 'สำรวจ',
    namecard: 'นามบัตร',
    events: 'กิจกรรม',
    exit: 'ออกจากห้อง',
    lieDown: 'นอนพัก',
    standUp: 'ลุกขึ้น',
    resting: 'กำลังพัก · ล็อกการเคลื่อนที่ · กด Esc เพื่อลุกขึ้น',
    closet: 'ตู้เสื้อผ้า',
    closetOpen: 'เปิดตู้เสื้อผ้า',
    closetClose: 'ปิดตู้เสื้อผ้า',
    fullPage: 'เปิดหน้าเว็บ',
    close: 'กลับไปที่ห้อง',
    examine: 'ตรวจดู',
    light: 'ไฟห้อง',
    lightOn: 'เปิดไฟ',
    lightOff: 'ปิดไฟ',
    lightLeft: 'ไฟซ้าย',
    lightRight: 'ไฟขวา',
    lightStateOn: 'เปิด',
    lightStateOff: 'ปิด',
    lightAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    curtains: 'ผ้าม่าน',
    curtainsOpen: 'เปิดผ้าม่าน',
    curtainsClose: 'ปิดผ้าม่าน',
    curtainsAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    related: 'หน้าที่เกี่ยวข้อง',
    content: 'เนื้อหาของหน้า',
    failed: 'โหลดห้องไม่สำเร็จ ยังสามารถอ่านทุกหน้าได้จากลิงก์ด้านล่าง',
    look: 'คลิกเพื่ออ่าน',
    about: 'เกี่ยวกับผม',
    contact: 'ติดต่อ',
    tags: 'แท็ก',
    piano: 'เปียโน',
    typing: 'ไทป์ปิง / สเตโน',
    darts: 'ปาเป้า',
    rubik: 'รูบิก',
    yoyo: 'โยโย่',
    penspinning: 'เพนสปินนิ่ง',
    kendama: 'เคนดามะ',
    cardistry: 'คาร์ดิสทรี / มายากล',
    dartsIntro: 'เล็งบนกระดานแล้วขว้าง',
    dartsScore: 'คะแนน',
    dartsThrows: 'จำนวนครั้ง',
    dartsReset: 'เริ่มเกมใหม่',
    dartsBoard: 'จุดเล็งบนกระดานปาเป้า',
    dartsAim: 'ตั้งเป้าแล้ว',
    dartsReady: 'เลือกจุดบนกระดานก่อน',
    dartsThrow: 'ขว้างปาเป้า',
    dartsResult: 'ผลลัพธ์',
    dartsBullseye: 'บูลส์อาย · 50',
    dartsOuter: 'วงนอก · 25',
    dartsSingle: 'ซิงเกิล · 10',
    dartsMiss: 'พลาด · 0',
    penlight: 'แท่งไฟเชียร์',
    games: {
      score: 'คะแนน',
      best: 'สูงสุด',
      combo: 'คอมโบ',
      start: 'เริ่ม',
      reset: 'รีเซ็ต',
      piano: {
        intro: 'เล่นด้วยเมาส์หรือปุ่ม A W S E D F T G Y H U J K O L P ;',
        playAlong: 'เล่นตามเพลง',
        progress: 'โน้ต',
        done: 'จบเพลงแล้ว'
      },
      typing: {
        intro: 'พิมพ์ประโยคให้เร็วและถูกต้องที่สุด',
        next: 'ประโยคถัดไป',
        wpm: 'WPM',
        accuracy: 'ความแม่นยำ',
        done: 'เสร็จแล้ว'
      },
      rubik: {
        intro: 'สุ่มสลับแล้วแก้ให้เสร็จ ใช้ปุ่มหรือคีย์ U D L R F B กด Shift เพื่อหมุนกลับ',
        scramble: 'สุ่มสลับ',
        moves: 'จำนวนครั้ง',
        time: 'เวลา',
        solved: 'สำเร็จ'
      },
      yoyo: {
        intro: 'โยนแล้วปล่อยให้หมุน ดึงกลับก่อนหยุดหมุน กด Space เพื่อโยนและดึงกลับ กด T เพื่อทำท่า',
        throw: 'โยน',
        bind: 'ดึงกลับ',
        trick: 'อะราวด์เดอะเวิลด์',
        dead: 'โยโย่หยุดหมุนแล้ว',
        spin: 'การหมุน'
      },
      penspinning: {
        intro: 'ส่งปากกาตอนผ่านส่วนโค้งที่เรืองแสง กด Space หรือคลิก',
        pass: 'ส่ง',
        drop: 'ทำหล่น',
        speed: 'ความเร็ว'
      },
      kendama: {
        intro: 'ดึงลูกขึ้นตอนแกว่งผ่านโซนเรืองแสง กด Space หรือคลิก',
        pull: 'ดึงขึ้น',
        big: 'ถ้วยใหญ่',
        small: 'ถ้วยเล็ก',
        spike: 'ปลายแหลม',
        miss: 'พลาด'
      },
      cardistry: {
        intro: 'จำไพ่เอซ ตามการสับ แล้วเลือกให้ถูก',
        deal: 'แจกไพ่',
        pick: 'เลือกไพ่',
        right: 'เจอเอซแล้ว',
        wrong: 'ไม่ใช่ใบนี้',
        level: 'ระดับ'
      },
      penlight: {
        intro: 'โบกสีเดียวกันตอนแสงทับวงกลม ใช้แผ่นสีหรือปุ่ม 1 ถึง 5',
        perfect: 'เพอร์เฟกต์',
        great: 'เกรท',
        miss: 'พลาด'
      }
    },
    blocked: 'ใช้ปุ่มลูกศรเพื่อมองรอบห้อง ใช้ WASD เพื่อเดิน'
  }
};
