export const roomCopy = {
  en: {
    room: 'My room',
    scene: 'An interactive 3D room',
    welcome: 'Come on in',
    title: 'A room of my own.',
    intro: 'Work on the monitor. Notes on the desk. Hobbies on the shelf. Take a look around.',
    enter: 'Enter room',
    loading: 'Preparing the room…',
    loadingDescription: 'Loading…',
    conventional: 'Browse the website',
    controls:
      'Click the canvas to lock cursor · WASD to move · Mouse or arrows to look · Click an object to explore',
    mobileControls: 'Drag to look · Tap the floor to move · Tap an object to explore',
    destinations: 'Explore',
    namecard: 'Namecard',
    events: 'Events',
    exit: 'Leave room',
    lieDown: 'Lie down',
    standUp: 'Stand up',
    resting: 'Resting · movement locked · Esc to stand up',
    closet: 'Closet',
    closetOpen: 'Open closet',
    closetClose: 'Close closet',
    fullPage: 'Open page',
    close: 'Return to room',
    examine: 'Examine',
    light: 'Light',
    lightOn: 'Turn lights on',
    lightOff: 'Turn lights off',
    lightLeft: 'Left light',
    lightRight: 'Right light',
    lightStateOn: 'On',
    lightStateOff: 'Off',
    lightAuto: 'Tokyo automatic',
    curtains: 'Curtains',
    curtainsOpen: 'Open curtains',
    curtainsClose: 'Close curtains',
    curtainsAuto: 'Tokyo automatic',
    related: 'Related pages',
    content: 'Page content',
    failed: 'The room could not load. You can still explore every page below.',
    look: 'Click to explore',
    about: 'About',
    contact: 'Contact',
    tags: 'Tags',
    piano: 'Piano',
    typing: 'Typing / Steno',
    darts: 'Darts',
    rubik: 'Rubik',
    yoyo: 'Yoyo',
    penspinning: 'Pen Spinning',
    kendama: 'Kendama',
    cardistry: 'Cardistry / Magic',
    dartsIntro: 'Aim on the board, then throw',
    dartsScore: 'Score',
    dartsThrows: 'Throws',
    dartsReset: 'Reset game',
    dartsBoard: 'Dartboard aiming surface',
    dartsAim: 'Aim set',
    dartsReady: 'Choose a spot on the board.',
    dartsThrow: 'Throw dart',
    dartsResult: 'Result',
    dartsBullseye: 'Bullseye · 50',
    dartsOuter: 'Outer bull · 25',
    dartsSingle: 'Single · 10',
    dartsMiss: 'Miss · 0',
    blocked: 'Arrow keys look around. WASD moves through the room.'
  },
  ja: {
    room: '私の部屋',
    scene: '操作できる3Dの部屋',
    welcome: 'ようこそ',
    title: '私の部屋へ。',
    intro: 'モニターには制作物。机にはノート。棚には趣味。自由に見て回ってください。',
    enter: '部屋に入る',
    loading: '部屋を準備しています…',
    loadingDescription: '読み込み中…',
    conventional: '通常のサイトを見る',
    controls:
      'キャンバスをクリックしてカーソルを固定 · WASDで移動 · マウス/矢印で見回す · 物をクリックして読む',
    mobileControls: 'ドラッグで見回す · 床をタップして移動 · 物をタップして読む',
    destinations: 'コンテンツ',
    namecard: '名刺',
    events: 'イベント',
    exit: '部屋を出る',
    lieDown: '横になる',
    standUp: '起き上がる',
    resting: '休憩中 · 移動固定 · Escで起き上がる',
    closet: 'クローゼット',
    closetOpen: 'クローゼットを開く',
    closetClose: 'クローゼットを閉じる',
    fullPage: 'ページを開く',
    close: '部屋に戻る',
    examine: '調べる',
    light: '照明',
    lightOn: '照明を点ける',
    lightOff: '照明を消す',
    lightLeft: '左の照明',
    lightRight: '右の照明',
    lightStateOn: '点灯',
    lightStateOff: '消灯',
    lightAuto: '東京時刻に戻す',
    curtains: 'カーテン',
    curtainsOpen: 'カーテンを開く',
    curtainsClose: 'カーテンを閉じる',
    curtainsAuto: '東京時刻に戻す',
    related: '関連ページ',
    content: 'ページの内容',
    failed: '部屋を読み込めませんでした。下のリンクから各ページをご覧いただけます。',
    look: 'クリックして読む',
    about: '自己紹介',
    contact: 'お問い合わせ',
    tags: 'タグ',
    piano: 'ピアノ',
    typing: 'タイピング / ステノ',
    darts: 'ダーツ',
    rubik: 'ルービックキューブ',
    yoyo: 'ヨーヨー',
    penspinning: 'ペンスピニング',
    kendama: 'けん玉',
    cardistry: 'カーディストリー / マジック',
    dartsIntro: 'ボードを狙ってから投げてください',
    dartsScore: 'スコア',
    dartsThrows: '投数',
    dartsReset: 'ゲームをリセット',
    dartsBoard: '狙うダーツボード',
    dartsAim: '狙いを設定',
    dartsReady: 'ボード上の場所を選んでください。',
    dartsThrow: 'ダーツを投げる',
    dartsResult: '結果',
    dartsBullseye: 'ブルズアイ · 50',
    dartsOuter: 'アウターブル · 25',
    dartsSingle: 'シングル · 10',
    dartsMiss: 'ミス · 0',
    blocked: '矢印キーで見回せます。WASDで部屋を移動できます。'
  },
  th: {
    room: 'ห้องของผม',
    scene: 'ห้องสามมิติที่สำรวจได้',
    welcome: 'เชิญเข้ามาเลย',
    title: 'ห้องของผมเอง',
    intro: 'ผลงานอยู่ที่จอ บันทึกอยู่บนโต๊ะ งานอดิเรกอยู่บนชั้น ลองเดินดูได้เลย',
    enter: 'เข้าห้อง',
    loading: 'กำลังเตรียมห้อง…',
    loadingDescription: 'กำลังโหลด…',
    conventional: 'ดูเว็บไซต์แบบปกติ',
    controls:
      'คลิกแคนวาสเพื่อล็อกเคอร์เซอร์ · WASD เพื่อเดิน · เมาส์หรือปุ่มลูกศรเพื่อมอง · คลิกสิ่งของเพื่อดูเนื้อหา',
    mobileControls: 'ลากเพื่อมองรอบห้อง · แตะพื้นเพื่อเดิน · แตะสิ่งของเพื่อดูเนื้อหา',
    destinations: 'สำรวจ',
    namecard: 'นามบัตร',
    events: 'กิจกรรม',
    exit: 'ออกจากห้อง',
    lieDown: 'นอนพัก',
    standUp: 'ลุกขึ้น',
    resting: 'กำลังพัก · ล็อกการเคลื่อนที่ · กด Esc เพื่อลุกขึ้น',
    closet: 'ตู้เสื้อผ้า',
    closetOpen: 'เปิดตู้เสื้อผ้า',
    closetClose: 'ปิดตู้เสื้อผ้า',
    fullPage: 'เปิดหน้าเว็บ',
    close: 'กลับไปที่ห้อง',
    examine: 'ตรวจดู',
    light: 'ไฟห้อง',
    lightOn: 'เปิดไฟ',
    lightOff: 'ปิดไฟ',
    lightLeft: 'ไฟซ้าย',
    lightRight: 'ไฟขวา',
    lightStateOn: 'เปิด',
    lightStateOff: 'ปิด',
    lightAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    curtains: 'ผ้าม่าน',
    curtainsOpen: 'เปิดผ้าม่าน',
    curtainsClose: 'ปิดผ้าม่าน',
    curtainsAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    related: 'หน้าที่เกี่ยวข้อง',
    content: 'เนื้อหาของหน้า',
    failed: 'โหลดห้องไม่สำเร็จ ยังสามารถอ่านทุกหน้าได้จากลิงก์ด้านล่าง',
    look: 'คลิกเพื่ออ่าน',
    about: 'เกี่ยวกับผม',
    contact: 'ติดต่อ',
    tags: 'แท็ก',
    piano: 'เปียโน',
    typing: 'ไทป์ปิง / สเตโน',
    darts: 'ปาเป้า',
    rubik: 'รูบิก',
    yoyo: 'โยโย่',
    penspinning: 'เพนสปินนิ่ง',
    kendama: 'เคนดามะ',
    cardistry: 'คาร์ดิสทรี / มายากล',
    dartsIntro: 'เล็งบนกระดานแล้วขว้าง',
    dartsScore: 'คะแนน',
    dartsThrows: 'จำนวนครั้ง',
    dartsReset: 'เริ่มเกมใหม่',
    dartsBoard: 'จุดเล็งบนกระดานปาเป้า',
    dartsAim: 'ตั้งเป้าแล้ว',
    dartsReady: 'เลือกจุดบนกระดานก่อน',
    dartsThrow: 'ขว้างปาเป้า',
    dartsResult: 'ผลลัพธ์',
    dartsBullseye: 'บูลส์อาย · 50',
    dartsOuter: 'วงนอก · 25',
    dartsSingle: 'ซิงเกิล · 10',
    dartsMiss: 'พลาด · 0',
    blocked: 'ใช้ปุ่มลูกศรเพื่อมองรอบห้อง ใช้ WASD เพื่อเดิน'
  }
};
