export const roomCopy = {
  en: {
    room: 'My room',
    scene: 'An interactive 3D room',
    welcome: 'Come on in',
    title: 'A room of my own.',
    intro: 'Work on the monitor. Notes on the desk. Hobbies on the shelf. Take a look around.',
    enter: 'Enter room',
    loading: 'Preparing the room…',
    loadingDescription: 'Loading…',
    conventional: 'Browse the website',
    controls:
      'Click the canvas to lock cursor · WASD to move · Mouse or arrows to look · Click an object to explore',
    mobileControls: 'Drag to look · Tap the floor to move · Tap an object to explore',
    destinations: 'Explore',
    namecard: 'Namecard',
    events: 'Events',
    exit: 'Leave room',
    lieDown: 'Lie down',
    standUp: 'Stand up',
    resting: 'Resting · movement locked · Esc to stand up',
    closet: 'Closet',
    closetOpen: 'Open closet',
    closetClose: 'Close closet',
    fullPage: 'Open page',
    close: 'Return to room',
    examine: 'Examine',
    light: 'Light',
    lightOn: 'Turn lights on',
    lightOff: 'Turn lights off',
    lightLeft: 'Left light',
    lightRight: 'Right light',
    lightStateOn: 'On',
    lightStateOff: 'Off',
    lightAuto: 'Tokyo automatic',
    curtains: 'Curtains',
    curtainsOpen: 'Open curtains',
    curtainsClose: 'Close curtains',
    curtainsAuto: 'Tokyo automatic',
    related: 'Related pages',
    content: 'Page content',
    failed: 'The room could not load. You can still explore every page below.',
    look: 'Click to explore',
    about: 'About',
    contact: 'Contact',
    tags: 'Tags',
    piano: 'Piano',
    typing: 'Typing / Steno',
    darts: 'Darts',
    rubik: 'Rubik',
    yoyo: 'Yoyo',
    penspinning: 'Pen Spinning',
    kendama: 'Kendama',
    cardistry: 'Cardistry / Magic',
    nesoberi: 'Nesoberi',
    penlight: 'Penlights',
    play: {
      exit: 'Back to the room',
      openPage: 'Open page',
      darts: {
        intro:
          'Aim with the pointer. Press and hold to wind up, release to throw. Space works too. 301, finish on a double.',
        remaining: 'Left',
        round: 'Round',
        bust: 'Bust',
        win: 'Checkout!',
        newGame: 'New game',
        miss: 'Miss'
      },
      rubik: {
        intro:
          "csTimer keyboard: J F = U U', I K = R R', D E = L L', H G = F F', S L = D D', W O = B B', ; A = y y', T B = x x', P Q = z z'. Or drag across the cube. Space scrambles and the timer starts on your first turn.",
        scramble: 'Scramble',
        reset: 'Reset',
        time: 'Time',
        best: 'Best',
        ao5: 'ao5',
        solved: 'Solved',
        moves: 'Moves'
      }
    },
    blocked: 'Arrow keys look around. WASD moves through the room.'
  },
  ja: {
    room: '私の部屋',
    scene: '操作できる3Dの部屋',
    welcome: 'ようこそ',
    title: '私の部屋へ。',
    intro: 'モニターには制作物。机にはノート。棚には趣味。自由に見て回ってください。',
    enter: '部屋に入る',
    loading: '部屋を準備しています…',
    loadingDescription: '読み込み中…',
    conventional: '通常のサイトを見る',
    controls:
      'キャンバスをクリックしてカーソルを固定 · WASDで移動 · マウス/矢印で見回す · 物をクリックして読む',
    mobileControls: 'ドラッグで見回す · 床をタップして移動 · 物をタップして読む',
    destinations: 'コンテンツ',
    namecard: '名刺',
    events: 'イベント',
    exit: '部屋を出る',
    lieDown: '横になる',
    standUp: '起き上がる',
    resting: '休憩中 · 移動固定 · Escで起き上がる',
    closet: 'クローゼット',
    closetOpen: 'クローゼットを開く',
    closetClose: 'クローゼットを閉じる',
    fullPage: 'ページを開く',
    close: '部屋に戻る',
    examine: '調べる',
    light: '照明',
    lightOn: '照明を点ける',
    lightOff: '照明を消す',
    lightLeft: '左の照明',
    lightRight: '右の照明',
    lightStateOn: '点灯',
    lightStateOff: '消灯',
    lightAuto: '東京時刻に戻す',
    curtains: 'カーテン',
    curtainsOpen: 'カーテンを開く',
    curtainsClose: 'カーテンを閉じる',
    curtainsAuto: '東京時刻に戻す',
    related: '関連ページ',
    content: 'ページの内容',
    failed: '部屋を読み込めませんでした。下のリンクから各ページをご覧いただけます。',
    look: 'クリックして読む',
    about: '自己紹介',
    contact: 'お問い合わせ',
    tags: 'タグ',
    piano: 'ピアノ',
    typing: 'タイピング / ステノ',
    darts: 'ダーツ',
    rubik: 'ルービックキューブ',
    yoyo: 'ヨーヨー',
    penspinning: 'ペンスピニング',
    kendama: 'けん玉',
    cardistry: 'カーディストリー / マジック',
    nesoberi: '寝そべり',
    penlight: 'ペンライト',
    play: {
      exit: '部屋に戻る',
      openPage: 'ページを開く',
      darts: {
        intro:
          'ポインターで狙い、押して構え、離して投げる。スペースキーでも可。301、ダブルで上がり。',
        remaining: '残り',
        round: 'ラウンド',
        bust: 'バースト',
        win: 'フィニッシュ！',
        newGame: '新しいゲーム',
        miss: 'ミス'
      },
      rubik: {
        intro:
          "csTimer キー配置：J F = U U'、I K = R R'、D E = L L'、H G = F F'、S L = D D'、W O = B B'、; A = y y'、T B = x x'、P Q = z z'。キューブをドラッグしても回せます。スペースでスクランブル、最初の一手で計測開始。",
        scramble: 'スクランブル',
        reset: 'リセット',
        time: 'タイム',
        best: 'ベスト',
        ao5: 'ao5',
        solved: '完成',
        moves: '手数'
      }
    },
    blocked: '矢印キーで見回せます。WASDで部屋を移動できます。'
  },
  th: {
    room: 'ห้องของผม',
    scene: 'ห้องสามมิติที่สำรวจได้',
    welcome: 'เชิญเข้ามาเลย',
    title: 'ห้องของผมเอง',
    intro: 'ผลงานอยู่ที่จอ บันทึกอยู่บนโต๊ะ งานอดิเรกอยู่บนชั้น ลองเดินดูได้เลย',
    enter: 'เข้าห้อง',
    loading: 'กำลังเตรียมห้อง…',
    loadingDescription: 'กำลังโหลด…',
    conventional: 'ดูเว็บไซต์แบบปกติ',
    controls:
      'คลิกแคนวาสเพื่อล็อกเคอร์เซอร์ · WASD เพื่อเดิน · เมาส์หรือปุ่มลูกศรเพื่อมอง · คลิกสิ่งของเพื่อดูเนื้อหา',
    mobileControls: 'ลากเพื่อมองรอบห้อง · แตะพื้นเพื่อเดิน · แตะสิ่งของเพื่อดูเนื้อหา',
    destinations: 'สำรวจ',
    namecard: 'นามบัตร',
    events: 'กิจกรรม',
    exit: 'ออกจากห้อง',
    lieDown: 'นอนพัก',
    standUp: 'ลุกขึ้น',
    resting: 'กำลังพัก · ล็อกการเคลื่อนที่ · กด Esc เพื่อลุกขึ้น',
    closet: 'ตู้เสื้อผ้า',
    closetOpen: 'เปิดตู้เสื้อผ้า',
    closetClose: 'ปิดตู้เสื้อผ้า',
    fullPage: 'เปิดหน้าเว็บ',
    close: 'กลับไปที่ห้อง',
    examine: 'ตรวจดู',
    light: 'ไฟห้อง',
    lightOn: 'เปิดไฟ',
    lightOff: 'ปิดไฟ',
    lightLeft: 'ไฟซ้าย',
    lightRight: 'ไฟขวา',
    lightStateOn: 'เปิด',
    lightStateOff: 'ปิด',
    lightAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    curtains: 'ผ้าม่าน',
    curtainsOpen: 'เปิดผ้าม่าน',
    curtainsClose: 'ปิดผ้าม่าน',
    curtainsAuto: 'ใช้เวลาโตเกียวอัตโนมัติ',
    related: 'หน้าที่เกี่ยวข้อง',
    content: 'เนื้อหาของหน้า',
    failed: 'โหลดห้องไม่สำเร็จ ยังสามารถอ่านทุกหน้าได้จากลิงก์ด้านล่าง',
    look: 'คลิกเพื่ออ่าน',
    about: 'เกี่ยวกับผม',
    contact: 'ติดต่อ',
    tags: 'แท็ก',
    piano: 'เปียโน',
    typing: 'ไทป์ปิง / สเตโน',
    darts: 'ปาเป้า',
    rubik: 'รูบิก',
    yoyo: 'โยโย่',
    penspinning: 'เพนสปินนิ่ง',
    kendama: 'เคนดามะ',
    cardistry: 'คาร์ดิสทรี / มายากล',
    nesoberi: 'ตุ๊กตาเนโซเบริ',
    penlight: 'แท่งไฟเชียร์',
    play: {
      exit: 'กลับไปที่ห้อง',
      openPage: 'เปิดหน้า',
      darts: {
        intro:
          'เล็งด้วยเมาส์ กดค้างเพื่อง้าง ปล่อยเพื่อปา หรือใช้ Space ก็ได้ เกม 301 ต้องจบด้วยช่องดับเบิล',
        remaining: 'เหลือ',
        round: 'รอบ',
        bust: 'บัสต์',
        win: 'ปิดเกม!',
        newGame: 'เริ่มใหม่',
        miss: 'พลาด'
      },
      rubik: {
        intro:
          "คีย์แบบ csTimer: J F = U U', I K = R R', D E = L L', H G = F F', S L = D D', W O = B B', ; A = y y', T B = x x', P Q = z z' หรือลากบนลูกบาศก์เพื่อหมุน กด Space เพื่อสุ่มสลับ จับเวลาเริ่มเมื่อหมุนครั้งแรก",
        scramble: 'สุ่มสลับ',
        reset: 'รีเซ็ต',
        time: 'เวลา',
        best: 'ดีที่สุด',
        ao5: 'ao5',
        solved: 'สำเร็จ',
        moves: 'จำนวนครั้ง'
      }
    },
    blocked: 'ใช้ปุ่มลูกศรเพื่อมองรอบห้อง ใช้ WASD เพื่อเดิน'
  }
};
